#!/usr/bin/env python3
"""Build samples/samples.xlsx from samples/samples.jsonl — one row per generator."""
import json
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
from openpyxl.utils import get_column_letter

CELL_MAX = 32767            # Excel's hard per-cell character limit
SAFE = 32000

rows = [json.loads(l) for l in open("samples/samples.jsonl")]
rows.sort(key=lambda r: (r["family"], r["paper"]))

wb = Workbook()

# ----------------------------------------------------------------- Samples
ws = wb.active
ws.title = "Samples"

HEAD = ["Paper", "Title", "Family", "arXiv URL", "Preset", "Parameters",
        "Verified", "Question chars", "Question truncated", "Search space (digits)",
        "Question", "Answer"]
ws.append(HEAD)

hfill = PatternFill("solid", fgColor="1F3864")
hfont = Font(name="Arial", size=10, bold=True, color="FFFFFF")
thin = Side(style="thin", color="BFBFBF")
border = Border(left=thin, right=thin, top=thin, bottom=thin)
for c in range(1, len(HEAD) + 1):
    cell = ws.cell(row=1, column=c)
    cell.fill = hfill; cell.font = hfont
    cell.alignment = Alignment(vertical="center", horizontal="center", wrap_text=True)
ws.row_dimensions[1].height = 30

for r in rows:
    q = r["question"]
    trunc = len(q) > CELL_MAX
    if trunc:
        q = q[:SAFE] + f"\n\n[TRUNCATED — full question ({len(r['question'])} chars) is in samples.jsonl]"
    ss = r.get("search_space") or ""
    ws.append([
        r["paper"], r["title"], r["family"], r["url"], r["preset"],
        json.dumps(r["params"]), "yes" if r["verified"] else "NO",
        len(r["question"]), "yes" if trunc else "", len(str(ss)) if ss else None,
        q, json.dumps(r["answer"], default=str),
    ])

body = Font(name="Arial", size=10)
mono = Font(name="Consolas", size=9)
for row in ws.iter_rows(min_row=2, max_row=ws.max_row, max_col=len(HEAD)):
    for cell in row:
        cell.font = body
        cell.border = border
        cell.alignment = Alignment(vertical="top", wrap_text=False)
    row[10].font = mono          # Question
    row[11].font = mono          # Answer
    row[3].font = Font(name="Arial", size=10, color="0563C1", underline="single")
    row[3].hyperlink = row[3].value
    row[6].alignment = Alignment(vertical="top", horizontal="center")
    row[7].number_format = "#,##0"
    row[9].number_format = "#,##0"

widths = {"A": 12, "B": 52, "C": 26, "D": 30, "E": 11, "F": 30, "G": 9,
          "H": 13, "I": 12, "J": 14, "K": 100, "L": 60}
for col, w in widths.items():
    ws.column_dimensions[col].width = w
ws.freeze_panes = "C2"
ws.auto_filter.ref = f"A1:{get_column_letter(len(HEAD))}{ws.max_row}"

# ----------------------------------------------------------------- Summary
s = wb.create_sheet("Summary")
n = ws.max_row
s["A1"] = "Generator sample set"; s["A1"].font = Font(name="Arial", size=13, bold=True)
s["A3"] = "Generators";              s["B3"] = f"=COUNTA(Samples!A2:A{n})"
s["A4"] = "Planted answers verified"; s["B4"] = f'=COUNTIF(Samples!G2:G{n},"yes")'
s["A5"] = "Families covered";        s["B5"] = f"=SUMPRODUCT((Samples!C2:C{n}<>\"\")/COUNTIF(Samples!C2:C{n},Samples!C2:C{n}&\"\"))"
s["A6"] = "Median question length";  s["B6"] = f"=MEDIAN(Samples!H2:H{n})"
s["A7"] = "Longest question";        s["B7"] = f"=MAX(Samples!H2:H{n})"
s["A8"] = "Questions truncated for Excel"; s["B8"] = f'=COUNTIF(Samples!I2:I{n},"yes")'

s["A10"] = "By family"; s["A10"].font = Font(name="Arial", size=11, bold=True)
s["A11"] = "Family"; s["B11"] = "Generators"
fams = sorted({r["family"] for r in rows})
for i, f in enumerate(fams):
    s.cell(row=12 + i, column=1, value=f)
    s.cell(row=12 + i, column=2, value=f'=COUNTIF(Samples!C2:C{n},A{12+i})')
last = 11 + len(fams)
s.cell(row=last + 1, column=1, value="Total")
s.cell(row=last + 1, column=2, value=f"=SUM(B12:B{last})")

for row in s.iter_rows(min_row=1, max_row=s.max_row, max_col=2):
    for cell in row:
        if cell.font.size is None or cell.font.size == 11:
            cell.font = Font(name="Arial", size=10)
for cell in ("A11", "B11", f"A{last+1}", f"B{last+1}"):
    s[cell].font = Font(name="Arial", size=10, bold=True)
s["A1"].font = Font(name="Arial", size=13, bold=True)
s["A10"].font = Font(name="Arial", size=11, bold=True)
s.column_dimensions["A"].width = 34
s.column_dimensions["B"].width = 14
s["B6"].number_format = "#,##0"; s["B7"].number_format = "#,##0"

# ----------------------------------------------------------------- Notes
nt = wb.create_sheet("Notes")
nt["A1"] = "Provenance and caveats"; nt["A1"].font = Font(name="Arial", size=13, bold=True)
notes = [
 "",
 "Source: samples/samples.jsonl, generated by scripts/samples.py from the repo's shipped generators.",
 "Each question is render(make_instance(seed=42, **DIFFICULTY[SHIPPING_DIFFICULTY])) for that module.",
 "Every answer in column L is the planted answer, checked with that module's own verify() before export.",
 "",
 "TRUNCATION",
 "Excel caps a cell at 32,767 characters. One question (2104.04330, 67,175 chars) exceeds that and is",
 "cut at 32,000 with a marker; column I flags it. The complete text is in samples.jsonl.",
 "",
 "SEARCH SPACE",
 "Column J reports the NUMBER OF DIGITS of search_space(inst), not the value: several exceed 10^300 and",
 "would lose precision as Excel numbers. Full values are in samples.jsonl.",
 "",
 "WHAT THIS FILE DOES AND DOES NOT ESTABLISH",
 "It shows each generator produces a self-contained, parseable question whose planted answer verifies.",
 "It is NOT evidence the problems are hard. G6 required only generic attacks (outlier/greedy/restart)",
 "until commit 606332e; 24 of these 39 shipped under the old rule. When the domain-standard attack was",
 "run against five such families, all five broke and were withdrawn (see AUDIT.md). Treat any row whose",
 "generator predates that commit as unaudited for hardness.",
]
for i, t in enumerate(notes, start=2):
    nt.cell(row=i, column=1, value=t).font = Font(
        name="Arial", size=10, bold=t.isupper() and bool(t))
nt.column_dimensions["A"].width = 112

wb.save("samples/samples.xlsx")
print(f"wrote samples/samples.xlsx: {n-1} rows, {len(fams)} families")
